# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      keycloak:
        patterns:
          - "org.keycloak.*"
      maven:
        patterns:
          - "org.apache.maven.*"
      junit:
        patterns:
          - "org.junit.*"
          
  - package-ecosystem: "docker"
    directory: "/testing/manifests"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/.github"
    schedule:
      interval: "weekly"
