services:

  openbao:
    image: ghcr.io/openbao/openbao:2.2.1

    environment:
      - BAO_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - BAO_DEV_ROOT_TOKEN_ID=my-root-token
      - BAO_LOG_LEVEL=debug

    ports:
      - "8200:8200"

    volumes:
      - shared-data:/var/run/secrets/kubernetes.io/serviceaccount/

  coordinator:
    image: eclipse-temurin:21-alpine
    entrypoint: ["java", "-Djava.util.logging.manager=org.jboss.logmanager.LogManager", "-jar", "/app.jar"]

    volumes:
      - ./testing/coordinator/target/coordinator-1.0-SNAPSHOT.jar:/app.jar:ro
      - shared-data:/shared

    networks:
      default:
        aliases:
          - kubernetes

  keycloak:
    image: quay.io/keycloak/keycloak:${KEYCLOAK_VERSION}

    entrypoint: /bin/bash
    command:
      - -cxe
      - |
        mkdir -p /var/run/secrets/kubernetes.io/serviceaccount
        echo -n my-root-token > /var/run/secrets/kubernetes.io/serviceaccount/token
        /opt/keycloak/bin/kc.sh start-dev \
          --import-realm \
          --spi-vault-provider=secrets-provider \
          --spi-vault-secrets-provider-address=http://openbao:8200 \
          --spi-vault-secrets-provider-kv-secret-path=secret/keycloak \
          --spi-vault-secrets-provider-kv-version=2 \
          --log-level=INFO,io.github.nordix.keycloak.services.vault:debug

    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=http://keycloak.127.0.0.1.nip.io:8080
      - KC_HTTP_ENABLED=true

    ports:
      - "8080:8080"

    volumes:
      - ./secrets-provider/src/test/resources/integration-test/realms:/opt/keycloak/data/import:ro
      - ${EXTENSION_JAR_PATH}:/opt/keycloak/providers/keycloak-secrets-provider.jar:ro
      - shared-data:/shared

    tmpfs:
      - /var/run/secrets

volumes:
  shared-data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=64m,uid=1000
